### ISSUE TITLE
Version 0.2 published in crates.io cannot be built anymore due to transitive dependency on quote 1.0.3

### ISSUE THREAD

**Issue by ancwrd1** [mullvad/windows-service-rs#43]
The `quote` crate was updated to 1.0.3 which broke older version of `err-derive` which is a dependency on published `windows-service 0.2`.

Using git repository directly as a dependency fixes the problem.

**Comment by nbigaouette** [comment]
`windows-service`'s commit e22e6d8281291a227b8f375fa13685be6ca8b146 has bumped the dependency on `err-derive` to 0.2.1, which should fix this.

Unfortunately, a new version was not released to crates.io (which is still at 0.2.0 from a year ago).

@faern Could a new release be made to crates.io? Until then we'll continue to need to add something like this to Cargo.toml:

```toml
[patch.crates-io]
windows-service = { git = 'https://github.com/mullvad/windows-service-rs.git', ref ="202d88bf438fdb870f4fc26e2031d36ab083fc42" }
```
